feat(integration-tests): Add integration test for war deployment
This sets up an external tomcat in a podman container that starts ors via systemd/war deployment. Additionally, checks are executed against the container to see if the env variables are read properly.

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -8,37 +8,102 @@ on:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
+env:
+  TEST_IMAGE_NAME: 'local/tomcat-test:latest'
+  BUILD_PLATFORMS: 'linux/amd64'
+
 
 jobs:
-#  debian-12-tomcat-war-systemd:
-#    name: Run Debian 12 Tomcat WAR systemd integration tests
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#        with:
-#          fetch-depth: 0
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v2
-#        id: buildx
-#        with:
-#          install: true
-#      - name: Set up JDK 17
-#        uses: actions/setup-java@v2
-#        with:
-#          distribution: 'temurin'
-#          java-version: '17'
-#      - name: Cache Maven packages
-#        uses: actions/cache@v4
-#        with:
-#          path: ~/.m2
-#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-#          restore-keys: ${{ runner.os }}-m2
-#      #      - name: Maven dependency resolution in ~/.m2
-#      #        run: |
-#      #          mvn dependency:go-offline -Dmaven.repo.local=~/.m2
-#      #          mvn clean
-#      - name: Run integration tests
-#        run: ./.integration-scenarios/debian-12-tomcat-war-systemd/run.sh -t -p
+  # This way the env variables are accessible in the individual jobs
+  prepare_environment:
+    name: Prepare the environment variables
+    runs-on: ubuntu-latest
+    outputs:
+      test_image_name: ${{ env.TEST_IMAGE_NAME }}
+      build_platforms: ${{ env.BUILD_PLATFORMS }}
+    steps:
+      - run: |
+          echo "Publish environment variables"
+  container-build-cache:
+    name: Docker Buildx cache
+    runs-on: ubuntu-latest
+    needs: prepare_environment
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+        id: buildx
+        with:
+          install: true
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+          cache: 'maven'
+      - name: Cache the docker image
+        uses: actions/cache@v4
+        with:
+          path: /tmp/tomcat-test.tar
+          key: ${{ runner.os }}-tomcat-test-${{ needs.prepare_environment.outputs.test_image_name }}
+          restore-keys: |
+            ${{ runner.os }}-tomcat-test-
+      - name: Load the docker image from cache if available
+        run: |
+          if [ -f /tmp/tomcat-test.tar ]; then
+              podman load -i /tmp/tomcat-test.tar || echo "Could not load the image from cache. Building it."
+          fi
+      - name: Build the podman image for changes
+        run: |
+          ./.integration-scenarios/debian-12-tomcat-war-systemd/run.sh -i ${{ needs.prepare_environment.outputs.test_image_name }}
+      - name: Export the podman image again
+        run: |
+          podman save -o /tmp/tomcat-test.tar ${{ needs.prepare_environment.outputs.test_image_name }}
+  debian-12-tomcat-war-systemd:
+    name: Run Debian 12 Tomcat WAR systemd integration tests
+    runs-on: ubuntu-latest
+    needs:
+      - prepare_environment
+      - container-build-cache
+    strategy:
+      matrix:
+        scenario: [ '0_*.sh', '1_*.sh', '2_*.sh' ]
+        image: [ ubuntu-latest ]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+        id: buildx
+        with:
+          install: true
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+          cache: 'maven'
+      - name: Cache the docker image
+        uses: actions/cache@v4
+        with:
+          path: /tmp/tomcat-test.tar
+          key: ${{ runner.os }}-tomcat-test-${{ needs.prepare_environment.outputs.test_image_name }}
+          restore-keys: |
+            ${{ runner.os }}-tomcat-test-
+      - name: Load the docker image from cache if available
+        run: |
+          if [ -f /tmp/tomcat-test.tar ]; then
+              podman load -i /tmp/tomcat-test.tar || { echo "Could not load the image from cache. Building it."; exit 1; }
+          fi
+      - name: Run integration tests
+        run: ./.integration-scenarios/debian-12-tomcat-war-systemd/run.sh -t -g '${{ matrix.scenario }}'
+
   debian-12-jar-mvn-build-docker:
     name: Update dependencies in maven cache
     runs-on: ubuntu-latest
@@ -64,24 +129,6 @@ jobs:
           restore-keys: ${{ runner.os }}-m2
       - name: Build Docker Images for jar and mvn
         run: mvn clean package -DskipTests
-#  debian-12-jar-mvn-build-graphs:
-#    name: Build Graphs with mvn and jar
-#    needs: debian-12-jar-mvn-build-docker
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#        with:
-#          fetch-depth: 0
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v2
-#        id: buildx
-#        with:
-#          install: true
-#      - name: Build Docker Images for jar and mvn
-##        run: ./.integration-scenarios/debian-12-jar-mvn/run.sh -mjt 'build-graph-*'
-#        run: |
-#          ./.integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-electric.sh jar
-#          ./.integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-mountain.sh mvn
   debian-12-jar-mvn-run-tests:
     needs: debian-12-jar-mvn-build-docker
     name: Run Debian 12 Maven JAR integration tests
